[workspace]
members = ["arrays", "bikestat", "biketime", "fileinfo", "input", "mpsc", "mutex", "networkclient", "networkserver", "primitives", "referencing", "referencing_2", "resultmatching", "threads"]
resolver = "2"