[package]
name = "biketool"
version = "0.1.1"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
chrono = "0.4.37"
regex = "1.10.4"
homedir = "0.2.1"

[[bin]]
name = "biketime"
path = "src/biketime.rs"