[package]
name = "biketool"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.7", features = ["derive"] }
chrono = "0.4.31"
regex = "1.10.2"

[[bin]]
name = "bikestat"
path = "src/bikestat.rs"

[[bin]]
name = "biketime"
path = "src/biketime.rs"